all: build-duckdb build-duckdb-arrow build-pg build-sqlite build-sources
  echo "All done"

all-ci: build-duckdb build-duckdb-arrow build-sqlite build-sources
  echo "All done"

build-duckdb:
  pnpm sqg tests/test-duckdb.yaml

build-duckdb-arrow:
  pnpm sqg tests/test-duckdb-arrow.yaml

build-pg:
  pnpm sqg tests/test-pg.yaml

build-sqlite:
  pnpm sqg tests/test-sqlite.yaml

build-sources: create-users-sqlite
  pnpm sqg tests/test-sources.yaml

start-pg: 
  docker run --name sqg-postgres -p 15432:5432 -e POSTGRES_PASSWORD=secret -e POSTGRES_USER=sqg -e POSTGRES_DB=sqg-db -d postgres

stop-pg:
  docker stop sqg-postgres
  docker rm sqg-postgres

create-users-sqlite:
  cd tests && rm -f users.sqlite && duckdb < users.sql

install:
  pnpm build
  pnpm add --global $(pwd)

release:
  #!/bin/bash
  pnpm version minor
  PACKAGE_VERSION="v$(pnpm pkg get version | tr -d '"')"
  git commit -m "release: $PACKAGE_VERSION" package.json
  git tag $PACKAGE_VERSION
  git push && git push --tags

  
