// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  File = 1,
  LineComment = 2,
  BlockComment = 3,
  BR = 4,
  QueryBlock = 5,
  BlockCommentStartSpecial = 6,
  Name = 7,
  Modifiers = 8,
  Config = 9,
  LineCommentStartSpecial = 10,
  SetVarLine = 11,
  Value = 12,
  StringLiteral = 13,
  StringLiteralSingle = 14,
  SQLText = 15,
  SQLBlock = 16,
  VarRef = 17
