packages:
  - sqg
  - website

catalog:
  '@duckdb/node-api': ^1.4.2-r.1
  '@duckdb/node-bindings-linux-x64': ^1.4.2-r.1

onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - esbuild
  - sharp

injectWorkspacePackages: true

