packages:
  - sqg
  - website

catalog:
  '@astrojs/check': ^0.9.6
  '@astrojs/node': ^9.5.1
  '@astrojs/starlight': ^0.37.1
  '@astrojs/svelte': ^7.2.4
  '@biomejs/biome': 2.3.3
  '@codemirror/lang-sql': ^6.10.0
  '@codemirror/state': ^6.5.2
  '@codemirror/theme-one-dark': ^6.1.3
  '@codemirror/view': ^6.39.4
  '@duckdb/node-api': 1.4.3-r.1
  '@duckdb/node-bindings-linux-x64': 1.4.3-r.1
  '@epic-web/cachified': ^5.6.0
  '@lezer-unofficial/printer': ^1.0.1
  '@lezer/common': ^1.4.0
  '@lezer/generator': ^1.8.0
  '@lezer/lr': ^1.4.5
  '@plausible-analytics/tracker': ^0.4.4
  '@tailwindcss/vite': ^4.1.18
  '@types/better-sqlite3': ^7.6.13
  '@types/dockerode': ^3.3.47
  '@types/node': ^25.0.3
  '@types/pg': ^8.16.0
  '@vitest/ui': ^4.0.16
  astro: ^5.16.6
  astro-d2: ^0.8.1
  autoprefixer: ^10.4.23
  better-sqlite3: ^12.5.0
  codemirror: ^6.0.2
  commander: ^14.0.2
  consola: ^3.4.2
  dockerode: ^4.0.9
  dotenv: ^17.2.3
  es-toolkit: ^1.43.0
  handlebars: ^4.7.8
  lru-cache: ^11.2.4
  pg: ^8.16.3
  pg-types: ^4.1.0
  prettier: ^3.7.4
  prettier-plugin-java: ^2.7.7
  shiki: ^3.20.0
  starlight-blog: ^0.25.2
  svelte: ^5.46.0
  tailwindcss: ^4.1.18
  tsdown: 0.18.0
  tsx: ^4.21.0
  typescript: ^5.9.3
  vitest: ^4.0.16
  yaml: ^2.8.2
  zod: ^4.2.1

injectWorkspacePackages: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - esbuild
  - protobufjs
  - sharp
