// This file is generated by SQG. Do not edit manually.
import type { Database, RunResult, Statement } from "better-sqlite3";

export class Queries {
  private statements = new Map<string, Statement>();

  constructor(private db: Database) {}

  private prepare<
    BindParameters extends unknown[] | {} = unknown[],
    Result = unknown,
  >(id: string, query: string, isPluck = false) {
    let stmt = this.statements.get(id);
    if (!stmt) {
      stmt = this.db.prepare(query);
      if (isPluck) {
        stmt = stmt.pluck();
      }
      this.statements.set(id, stmt);
    }
    return stmt as Statement<BindParameters, Result>;
  }

  static getMigrations(): string[] {
    return [
      `CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);`,
      `CREATE TABLE IF NOT EXISTS posts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    title TEXT NOT NULL,
    content TEXT,
    published INTEGER DEFAULT 0,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);`,
    ];
  }

  static getQueryNames(): Map<string, keyof Queries> {
    return new Map([
      ["insertUser", "insertUser"],
      ["getUsers", "getUsers"],
      ["getUserById", "getUserById"],
      ["getUserByEmail", "getUserByEmail"],
      ["insertPost", "insertPost"],
      ["getPostsByUser", "getPostsByUser"],
      ["getPublishedPosts", "getPublishedPosts"],
      ["countUserPosts", "countUserPosts"],
    ]);
  }

  insertUser(name: string, email: string): RunResult {
    const stmt = this.prepare<[string, string], any>(
      "insertUser",
      "INSERT INTO users (name, email) VALUES ( ?, ?);",
    );
    return stmt.run(name, email);
  }
  getUsers(): {
    id: number;
    name: string;
    email: string;
    created_at: string | null;
  }[] {
    const stmt = this.prepare<
      [],
      { id: number; name: string; email: string; created_at: string | null }
    >("getUsers", "SELECT id, name, email, created_at FROM users;");
    return stmt.all();
  }
  getUserById(
    id: number,
  ):
    | { id: number; name: string; email: string; created_at: string | null }
    | undefined {
    const stmt = this.prepare<
      [number],
      { id: number; name: string; email: string; created_at: string | null }
    >(
      "getUserById",
      "SELECT id, name, email, created_at FROM users WHERE id =?;",
    );
    return stmt.get(id);
  }
  getUserByEmail(
    email: string,
  ):
    | { id: number; name: string; email: string; created_at: string | null }
    | undefined {
    const stmt = this.prepare<
      [string],
      { id: number; name: string; email: string; created_at: string | null }
    >(
      "getUserByEmail",
      "SELECT id, name, email, created_at FROM users WHERE email =?;",
    );
    return stmt.get(email);
  }
  insertPost(
    userId: number,
    title: string,
    content: string,
    published: number,
  ): RunResult {
    const stmt = this.prepare<[number, string, string, number], any>(
      "insertPost",
      `INSERT INTO posts (user_id, title, content, published)
VALUES ( ?, ?, ?, ?);`,
    );
    return stmt.run(userId, title, content, published);
  }
  getPostsByUser(
    userId: number,
  ): {
    id: number;
    user_id: number;
    title: string;
    content: string | null;
    published: number | null;
    created_at: string | null;
  }[] {
    const stmt = this.prepare<
      [number],
      {
        id: number;
        user_id: number;
        title: string;
        content: string | null;
        published: number | null;
        created_at: string | null;
      }
    >(
      "getPostsByUser",
      `SELECT id, user_id, title, content, published, created_at
FROM posts WHERE user_id =?;`,
    );
    return stmt.all(userId);
  }
  getPublishedPosts(): {
    id: number;
    title: string;
    content: string | null;
    created_at: string | null;
    author_name: string;
  }[] {
    const stmt = this.prepare<
      [],
      {
        id: number;
        title: string;
        content: string | null;
        created_at: string | null;
        author_name: string;
      }
    >(
      "getPublishedPosts",
      `SELECT p.id, p.title, p.content, p.created_at, u.name as author_name
FROM posts p
JOIN users u ON p.user_id = u.id
WHERE p.published = 1;`,
    );
    return stmt.all();
  }
  countUserPosts(userId: number): unknown | undefined {
    const stmt = this.prepare<[number], unknown>(
      "countUserPosts",
      "SELECT COUNT(*) FROM posts WHERE user_id =?;",
      true,
    );
    return stmt.get(userId);
  }
}
