import { readFileSync } from "node:fs";
import { basename, dirname } from "node:path";
import { beforeEach, describe, expect, it } from "vitest";
import { processProject } from "../src/sqltool";

function getSnapshotName(file: string): string {
  const dir = dirname(file);
  const parentDir = basename(dir);
  const fileName = basename(file);
  // Only add prefix for /tmp/ subdirectories (like /tmp/node/)
  // to disambiguate when same file is generated by different generators
  if (dir.startsWith("/tmp/") && parentDir !== "tmp") {
    return `${parentDir}-${fileName}`;
  }
  return fileName;
}

export async function handleProject(projectPath: string, expectedFiles: string[]) {
  const files = await processProject(projectPath);
  expect(files.map((file) => basename(file))).toEqual(expectedFiles);
  for (const file of files) {
    const fileContent = readFileSync(file, "utf-8");
    const snapshotFile = `./__snapshots__/${getSnapshotName(file)}.snapshot`;
    await expect(fileContent).toMatchFileSnapshot(snapshotFile);
  }
  return files;
}

describe("sqg", () => {
  beforeEach(() => {
    //generator = new JavaGenerator('test-template');
  });

  describe("processProject", () => {
    it("handle duckdb correctly", async () => {
      await handleProject("tests/test-duckdb.yaml", ["TestDuckdb.java", "test-duckdb.ts"]);
    });
    it("handle duckdb-arrow correctly", async () => {
      await handleProject("tests/test-duckdb-arrow.yaml", ["TestDuckDbArrow.java"]);
    });

    it("handle sources correctly", async () => {
      await handleProject("tests/test-sources.yaml", ["TestSources.java"]);
    });
  });

  describe("processProjectSqlite", () => {
    it("handle sqlite correctly", async () => {
      await handleProject("tests/test-sqlite.yaml", ["test-sqlite.ts", "TestSqlite.java"]);
    });
  });

  describe("processProjectNodeSqlite", () => {
    it("handle node-sqlite correctly", async () => {
      await handleProject("tests/test-node-sqlite.yaml", ["test-sqlite.ts"]);
    });
  });

  describe("processProjectLibsql", () => {
    it("handle libsql correctly", async () => {
      await handleProject("tests/test-libsql.yaml", ["test-sqlite.ts"]);
    });
  });

  describe("processProjectTurso", () => {
    it("handle turso correctly", async () => {
      await handleProject("tests/test-turso.yaml", ["test-sqlite.ts"]);
    });
  });
});
