// This file is generated by SQG (https://sqg.dev). Do not edit manually.
import type { Client, InArgs } from "@libsql/client";

interface RunResult {
  changes: number;
  lastInsertRowid: bigint;
}

export class TestSqlite {
  constructor(private client: Client) {}

  static getMigrations(): string[] {
    return [
      `create table  users (
    id text primary key,
    name text not null,
    email text unique
) strict;`,
    ];
  }

  static getQueryNames(): Map<string, keyof TestSqlite> {
    return new Map([
      ["users1", "users1"],
      ["users2", "users2"],
      ["users3", "users3"],
      ["users4", "users4"],
      ["users5", "users5"],
      ["users6", "users6"],
      ["users7", "users7"],
    ]);
  }

  async users1(): Promise<
    { id: string; name: string; email: string | null }[]
  > {
    const result = await this.client.execute({
      sql: "select * from users;",
      args: [] as InArgs,
    });
    return result.rows as unknown[] as {
      id: string;
      name: string;
      email: string | null;
    }[];
  }
  async users2(): Promise<string | undefined> {
    const result = await this.client.execute({
      sql: `select id from users where id = '1';`,
      args: [] as InArgs,
    });
    const row = result.rows[0];
    return row ? (Object.values(row)[0] as string) : undefined;
  }
  async users3(): Promise<string | undefined> {
    const result = await this.client.execute({
      sql: `select name from users where id = '1';`,
      args: [] as InArgs,
    });
    const row = result.rows[0];
    return row ? (Object.values(row)[0] as string) : undefined;
  }
  async users4(): Promise<{ email: string | null; name: string } | undefined> {
    const result = await this.client.execute({
      sql: `select email, name from users where id = '1';`,
      args: [] as InArgs,
    });
    return (result.rows as unknown[])[0] as
      | { email: string | null; name: string }
      | undefined;
  }
  async users5(): Promise<{ count: number; email: string | null }[]> {
    const result = await this.client.execute({
      sql: `select 10 count, email from users where id = '1';`,
      args: [] as InArgs,
    });
    return result.rows as unknown[] as {
      count: number;
      email: string | null;
    }[];
  }
  async users6(
    name: string,
  ): Promise<{ id: string; name: string; email: string } | undefined> {
    const result = await this.client.execute({
      sql: "SELECT * FROM users WHERE name =?",
      args: [name] as InArgs,
    });
    return (result.rows as unknown[])[0] as
      | { id: string; name: string; email: string }
      | undefined;
  }
  async users7(
    name: string,
  ): Promise<{ id: string; name: string; email: string | null }[]> {
    const result = await this.client.execute({
      sql: "SELECT * FROM users WHERE name =?",
      args: [name] as InArgs,
    });
    return result.rows as unknown[] as {
      id: string;
      name: string;
      email: string | null;
    }[];
  }
}
