// This file is generated by SQG (https://sqg.dev). Do not edit manually.
/* eslint-disable */
// biome-ignore-all lint: generated code
import type { Client, InArgs } from "@libsql/client";

interface RunResult {
  changes: number;
  lastInsertRowid: bigint;
}

export class TestSqlite {
  constructor(private client: Client) {}

  static getMigrations(): string[] {
    return [
      `create table  users (
    id text primary key,
    name text not null,
    email text unique
) strict;`,
      `create table bigints (
  id integer primary key,
  posts bigint,
  total bigint not null
);`,
    ];
  }

  static async applyMigrations(
    client: Client,
    projectName = "test-libsql",
  ): Promise<void> {
    await client.execute({
      sql: `CREATE TABLE IF NOT EXISTS _sqg_migrations (
                project TEXT NOT NULL,
                migration_id TEXT NOT NULL,
                applied_at TEXT NOT NULL DEFAULT (datetime('now')),
                PRIMARY KEY (project, migration_id)
            )`,
      args: [],
    });
    const tx = await client.transaction("write");
    try {
      const result = await tx.execute({
        sql: "SELECT migration_id FROM _sqg_migrations WHERE project = ?",
        args: [projectName],
      });
      const applied = new Set(result.rows.map((r) => r.migration_id as string));
      const migrations: [string, string][] = [
        [
          "1",
          `create table  users (
    id text primary key,
    name text not null,
    email text unique
) strict;`,
        ],
        [
          "2",
          `create table bigints (
  id integer primary key,
  posts bigint,
  total bigint not null
);`,
        ],
      ];
      for (const [id, sql] of migrations) {
        if (!applied.has(id)) {
          await tx.execute({ sql, args: [] });
          await tx.execute({
            sql: "INSERT INTO _sqg_migrations (project, migration_id) VALUES (?, ?)",
            args: [projectName, id],
          });
        }
      }
      await tx.commit();
    } catch (e) {
      await tx.rollback();
      throw e;
    }
  }

  static getQueryNames(): Map<string, keyof TestSqlite> {
    return new Map([
      ["users1", "users1"],
      ["users2", "users2"],
      ["users3", "users3"],
      ["allEmails", "allEmails"],
      ["existsAny", "existsAny"],
      ["countAll", "countAll"],
      ["castSum", "castSum"],
      ["existsNoSemi", "existsNoSemi"],
      ["countTrailingWs", "countTrailingWs"],
      ["getBigints", "getBigints"],
      ["users4", "users4"],
      ["users5", "users5"],
      ["users6", "users6"],
      ["users7", "users7"],
      ["reserved_word_test", "reservedWordTest"],
    ]);
  }

  async users1(): Promise<
    { id: string; name: string; email: string | null }[]
  > {
    const result = await this.client.execute({
      sql: "select * from users;",
      args: [] as InArgs,
    });
    return result.rows as unknown[] as {
      id: string;
      name: string;
      email: string | null;
    }[];
  }
  async users2(): Promise<string | undefined> {
    const result = await this.client.execute({
      sql: `select id from users where id = '1';`,
      args: [] as InArgs,
    });
    const row = result.rows[0];
    return row ? (Object.values(row)[0] as string) : undefined;
  }
  async users3(): Promise<string | undefined> {
    const result = await this.client.execute({
      sql: `select name from users where id = '1';`,
      args: [] as InArgs,
    });
    const row = result.rows[0];
    return row ? (Object.values(row)[0] as string) : undefined;
  }
  async allEmails(): Promise<(string | null)[]> {
    const result = await this.client.execute({
      sql: "select email from users;",
      args: [] as InArgs,
    });
    return result.rows.map((row) => Object.values(row)[0] as string | null);
  }
  async existsAny(): Promise<number | undefined> {
    const result = await this.client.execute({
      sql: `select exists(select 1 from users where id = '1');`,
      args: [] as InArgs,
    });
    const row = result.rows[0];
    return row ? (Object.values(row)[0] as number) : undefined;
  }
  async countAll(): Promise<number | undefined> {
    const result = await this.client.execute({
      sql: "select count(*) from users;",
      args: [] as InArgs,
    });
    const row = result.rows[0];
    return row ? (Object.values(row)[0] as number) : undefined;
  }
  async castSum(): Promise<number | undefined> {
    const result = await this.client.execute({
      sql: `select cast(count(*) as integer) as n from users where id = '1';`,
      args: [] as InArgs,
    });
    const row = result.rows[0];
    return row ? (Object.values(row)[0] as number) : undefined;
  }
  async existsNoSemi(): Promise<number | undefined> {
    const result = await this.client.execute({
      sql: `select exists(select 1 from users where id = '1')`,
      args: [] as InArgs,
    });
    const row = result.rows[0];
    return row ? (Object.values(row)[0] as number) : undefined;
  }
  async countTrailingWs(): Promise<number | undefined> {
    const result = await this.client.execute({
      sql: "select count(*) from users ;",
      args: [] as InArgs,
    });
    const row = result.rows[0];
    return row ? (Object.values(row)[0] as number) : undefined;
  }
  async getBigints(): Promise<
    { posts: number | null; total: number } | undefined
  > {
    const result = await this.client.execute({
      sql: "select posts, total from bigints where id = 1;",
      args: [] as InArgs,
    });
    return (result.rows as unknown[])[0] as
      | { posts: number | null; total: number }
      | undefined;
  }
  async users4(): Promise<{ email: string | null; name: string } | undefined> {
    const result = await this.client.execute({
      sql: `select email, name from users where id = '1';`,
      args: [] as InArgs,
    });
    return (result.rows as unknown[])[0] as
      | { email: string | null; name: string }
      | undefined;
  }
  async users5(): Promise<{ count: number; email: string | null }[]> {
    const result = await this.client.execute({
      sql: `select 10 count, email from users where id = '1';`,
      args: [] as InArgs,
    });
    return result.rows as unknown[] as {
      count: number;
      email: string | null;
    }[];
  }
  async users6(
    name: string,
  ): Promise<{ id: string; name: string; email: string } | undefined> {
    const result = await this.client.execute({
      sql: "SELECT * FROM users WHERE name =?",
      args: [name] as InArgs,
    });
    return (result.rows as unknown[])[0] as
      | { id: string; name: string; email: string }
      | undefined;
  }
  async users7(
    name: string,
  ): Promise<{ id: string; name: string; email: string | null }[]> {
    const result = await this.client.execute({
      sql: "SELECT * FROM users WHERE name =?",
      args: [name] as InArgs,
    });
    return result.rows as unknown[] as {
      id: string;
      name: string;
      email: string | null;
    }[];
  }
  async reservedWordTest(): Promise<
    { class: string; type: string } | undefined
  > {
    const result = await this.client.execute({
      sql: `SELECT name as class, email as type FROM users WHERE id = '1'`,
      args: [] as InArgs,
    });
    return (result.rows as unknown[])[0] as
      | { class: string; type: string }
      | undefined;
  }
}
