// This file is generated by SQG (https://sqg.dev). Do not edit manually.
import { DatabaseSync, StatementSync } from "node:sqlite";

interface RunResult {
  changes: number;
  lastInsertRowid: number;
}

export class TestSqlite {
  private statements = new Map<string, StatementSync>();

  constructor(private db: DatabaseSync) {}

  private prepare(id: string, query: string) {
    let stmt = this.statements.get(id);
    if (!stmt) {
      stmt = this.db.prepare(query);
      this.statements.set(id, stmt);
    }
    return stmt;
  }

  static getMigrations(): string[] {
    return [
      `create table  users (
    id text primary key,
    name text not null,
    email text unique
) strict;`,
    ];
  }

  static getQueryNames(): Map<string, keyof TestSqlite> {
    return new Map([
      ["users1", "users1"],
      ["users2", "users2"],
      ["users3", "users3"],
      ["users4", "users4"],
      ["users5", "users5"],
      ["users6", "users6"],
      ["users7", "users7"],
    ]);
  }

  users1(): { id: string; name: string; email: string | null }[] {
    const stmt = this.prepare("users1", "select * from users;");
    return stmt.all() as { id: string; name: string; email: string | null }[];
  }
  users2(): string | undefined {
    const stmt = this.prepare("users2", `select id from users where id = '1';`);
    const row = stmt.get() as Record<string, string> | undefined;
    return row ? Object.values(row)[0] : undefined;
  }
  users3(): string | undefined {
    const stmt = this.prepare(
      "users3",
      `select name from users where id = '1';`,
    );
    const row = stmt.get() as Record<string, string> | undefined;
    return row ? Object.values(row)[0] : undefined;
  }
  users4(): { email: string | null; name: string } | undefined {
    const stmt = this.prepare(
      "users4",
      `select email, name from users where id = '1';`,
    );
    return stmt.get() as { email: string | null; name: string } | undefined;
  }
  users5(): { count: number; email: string | null }[] {
    const stmt = this.prepare(
      "users5",
      `select 10 count, email from users where id = '1';`,
    );
    return stmt.all() as { count: number; email: string | null }[];
  }
  users6(
    name: string,
  ): { id: string; name: string; email: string } | undefined {
    const stmt = this.prepare("users6", "SELECT * FROM users WHERE name =?");
    return stmt.get(name) as
      | { id: string; name: string; email: string }
      | undefined;
  }
  users7(name: string): { id: string; name: string; email: string | null }[] {
    const stmt = this.prepare("users7", "SELECT * FROM users WHERE name =?");
    return stmt.all(name) as {
      id: string;
      name: string;
      email: string | null;
    }[];
  }
}
