// This file is generated by SQG (https://sqg.dev). Do not edit manually.
/* eslint-disable */
// biome-ignore-all lint: generated code
import {
  DuckDBListType,
  listValue,
  VARCHAR,
  INTEGER,
  BIGINT,
  DOUBLE,
  FLOAT,
  BOOLEAN,
  SMALLINT,
  TINYINT,
  type DuckDBConnection,
  type DuckDBMaterializedResult,
  type DuckDBAppender,
  type DuckDBDateValue,
  type DuckDBTimeValue,
  type DuckDBTimestampValue,
  type DuckDBBlobValue,
  type DuckDBValue,
} from "@duckdb/node-api";

export class TestParamTypes {
  constructor(private conn: DuckDBConnection) {}

  static getMigrations(): string[] {
    return [
      "create table events(day date, n integer, label text, big bigint);",
    ];
  }

  static async applyMigrations(
    conn: DuckDBConnection,
    projectName = "test-param-types",
  ): Promise<void> {
    await conn.run(`CREATE TABLE IF NOT EXISTS _sqg_migrations (
            project TEXT NOT NULL,
            migration_id TEXT NOT NULL,
            applied_at TIMESTAMP NOT NULL DEFAULT now(),
            PRIMARY KEY (project, migration_id)
        )`);
    await conn.run("BEGIN");
    try {
      const result = await conn.runAndReadAll(
        "SELECT migration_id FROM _sqg_migrations WHERE project = $1",
        [projectName],
      );
      const applied = new Set(result.getRows().map((row) => row[0] as string));
      const migrations: [string, string][] = [
        [
          "1",
          "create table events(day date, n integer, label text, big bigint);",
        ],
      ];
      for (const [id, sql] of migrations) {
        if (!applied.has(id)) {
          await conn.run(sql);
          await conn.run(
            "INSERT INTO _sqg_migrations (project, migration_id) VALUES ($1, $2)",
            [projectName, id],
          );
        }
      }
      await conn.run("COMMIT");
    } catch (e) {
      await conn.run("ROLLBACK");
      throw e;
    }
  }

  static getQueryNames(): Map<string, keyof TestParamTypes> {
    return new Map([
      ["insertNullable", "insertNullable"],
      ["ddlWithParam", "ddlWithParam"],
      ["castMinusParam", "castMinusParam"],
      ["strptimeParam", "strptimeParam"],
      ["castParam", "castParam"],
    ]);
  }

  async insertNullable(
    day: string,
    label: string | null,
    big: bigint | null,
  ): Promise<DuckDBMaterializedResult> {
    const sql = "insert into events(day, label, big) values (?::DATE, ?, ?);";
    return await this.conn.run(sql, [day, label, big]);
  }

  async ddlWithParam(seed: number): Promise<DuckDBMaterializedResult> {
    const sql = "create or replace temp table tmp as select ? as a;";
    return await this.conn.run(sql, [seed]);
  }

  async castMinusParam(
    since: string,
    days: number,
  ): Promise<{ n: number | null }[]> {
    const sql = "select n from events where day > (cast(? as DATE) - ?);";
    const reader = await this.conn.runAndReadAll(sql, [since, days]);
    return reader.getRowObjects() as { n: number | null }[];
  }

  async strptimeParam(since: string): Promise<{ n: number | null }[]> {
    const sql = `select n from events where day > strptime(?, '%Y-%m-%d');`;
    const reader = await this.conn.runAndReadAll(sql, [since]);
    return reader.getRowObjects() as { n: number | null }[];
  }

  async castParam(since: string): Promise<{ n: number | null }[]> {
    const sql = "select n from events where day > cast(? as DATE);";
    const reader = await this.conn.runAndReadAll(sql, [since]);
    return reader.getRowObjects() as { n: number | null }[];
  }
}
