# This file is generated by SQG (https://sqg.dev). Do not edit manually.
from __future__ import annotations

import duckdb
from dataclasses import dataclass
from typing import Any

@dataclass(frozen=True)
class CastMinusParamRow:
    n: int | None

@dataclass(frozen=True)
class StrptimeParamRow:
    n: int | None

@dataclass(frozen=True)
class CastParamRow:
    n: int | None


class TestParamTypes:
    def __init__(self, conn: duckdb.DuckDBPyConnection) -> None:
        self._conn = conn

    @staticmethod
    def get_migrations() -> list[str]:
        return [
            "create table events(day date, n integer, label text, big bigint);",
        ]

    @staticmethod
    def apply_migrations(conn: duckdb.DuckDBPyConnection, project_name: str = "test-param-types") -> None:
        conn.execute("""
            CREATE TABLE IF NOT EXISTS _sqg_migrations (
                project TEXT NOT NULL,
                migration_id TEXT NOT NULL,
                applied_at TIMESTAMP NOT NULL DEFAULT now(),
                PRIMARY KEY (project, migration_id)
            )""")
        conn.begin()
        try:
            applied = set(
                row[0]
                for row in conn.execute(
                    "SELECT migration_id FROM _sqg_migrations WHERE project = $1",
                    [project_name],
                ).fetchall()
            )
            migrations: list[tuple[str, str]] = [
                ("1", "create table events(day date, n integer, label text, big bigint);"),
            ]
            for mid, sql in migrations:
                if mid not in applied:
                    conn.execute(sql)
                    conn.execute(
                        "INSERT INTO _sqg_migrations (project, migration_id) VALUES ($1, $2)",
                        [project_name, mid],
                    )
            conn.commit()
        except Exception:
            conn.rollback()
            raise

    def insert_nullable(self, day: datetime.date, label: str | None, big: int | None) -> None:
        self._conn.execute(
            "insert into events(day, label, big) values ($1::DATE, $2, $3);", [day, label, big]
        )

    def ddl_with_param(self, seed: int) -> None:
        self._conn.execute(
            "create or replace temp table tmp as select $1 as a;", [seed]
        )

    def cast_minus_param(self, since: datetime.date, days: int) -> list[CastMinusParamRow]:
        rows = self._conn.execute(
            "select n from events where day > (cast($1 as DATE) - $2);", [since, days]
        ).fetchall()
        return [CastMinusParamRow(n=row[0]) for row in rows]

    def cast_minus_param_raw(self, since: datetime.date, days: int) -> list[tuple[Any, ...]]:
        return self._conn.execute(
            "select n from events where day > (cast($1 as DATE) - $2);", [since, days]
        ).fetchall()

    def strptime_param(self, since: str) -> list[StrptimeParamRow]:
        rows = self._conn.execute(
            """\
select n from events where day > strptime($1, '%Y-%m-%d');""", [since]
        ).fetchall()
        return [StrptimeParamRow(n=row[0]) for row in rows]

    def strptime_param_raw(self, since: str) -> list[tuple[Any, ...]]:
        return self._conn.execute(
            """\
select n from events where day > strptime($1, '%Y-%m-%d');""", [since]
        ).fetchall()

    def cast_param(self, since: datetime.date) -> list[CastParamRow]:
        rows = self._conn.execute(
            "select n from events where day > cast($1 as DATE);", [since]
        ).fetchall()
        return [CastParamRow(n=row[0]) for row in rows]

    def cast_param_raw(self, since: datetime.date) -> list[tuple[Any, ...]]:
        return self._conn.execute(
            "select n from events where day > cast($1 as DATE);", [since]
        ).fetchall()








