// This file is generated by SQG (https://sqg.dev). Do not edit manually.
import { connect, type Database } from "@tursodatabase/database";

interface RunResult {
  changes: number;
  lastInsertRowid: number;
}

// Statement type inferred from Database.prepare()
type Statement = Awaited<ReturnType<Database["prepare"]>>;

export class TestSqlite {
  private statements = new Map<string, Statement>();

  constructor(private db: Database) {}

  private async prepare(id: string, query: string): Promise<Statement> {
    let stmt = this.statements.get(id);
    if (!stmt) {
      stmt = await this.db.prepare(query);
      this.statements.set(id, stmt);
    }
    return stmt;
  }

  static getMigrations(): string[] {
    return [
      `create table  users (
    id text primary key,
    name text not null,
    email text unique
) strict;`,
    ];
  }

  static getQueryNames(): Map<string, keyof TestSqlite> {
    return new Map([
      ["users1", "users1"],
      ["users2", "users2"],
      ["users3", "users3"],
      ["users4", "users4"],
      ["users5", "users5"],
      ["users6", "users6"],
      ["users7", "users7"],
    ]);
  }

  async users1(): Promise<
    { id: string; name: string; email: string | null }[]
  > {
    const stmt = await this.prepare("users1", "select * from users;");
    return (await stmt.all()) as {
      id: string;
      name: string;
      email: string | null;
    }[];
  }
  async users2(): Promise<string | undefined> {
    const stmt = await this.prepare(
      "users2",
      `select id from users where id = '1';`,
    );
    const row = (await stmt.get()) as Record<string, string> | undefined;
    return row ? Object.values(row)[0] : undefined;
  }
  async users3(): Promise<string | undefined> {
    const stmt = await this.prepare(
      "users3",
      `select name from users where id = '1';`,
    );
    const row = (await stmt.get()) as Record<string, string> | undefined;
    return row ? Object.values(row)[0] : undefined;
  }
  async users4(): Promise<{ email: string | null; name: string } | undefined> {
    const stmt = await this.prepare(
      "users4",
      `select email, name from users where id = '1';`,
    );
    return (await stmt.get()) as
      | { email: string | null; name: string }
      | undefined;
  }
  async users5(): Promise<{ count: number; email: string | null }[]> {
    const stmt = await this.prepare(
      "users5",
      `select 10 count, email from users where id = '1';`,
    );
    return (await stmt.all()) as { count: number; email: string | null }[];
  }
  async users6(
    name: string,
  ): Promise<{ id: string; name: string; email: string } | undefined> {
    const stmt = await this.prepare(
      "users6",
      "SELECT * FROM users WHERE name =?",
    );
    return (await stmt.get(name)) as
      | { id: string; name: string; email: string }
      | undefined;
  }
  async users7(
    name: string,
  ): Promise<{ id: string; name: string; email: string | null }[]> {
    const stmt = await this.prepare(
      "users7",
      "SELECT * FROM users WHERE name =?",
    );
    return (await stmt.all(name)) as {
      id: string;
      name: string;
      email: string | null;
    }[];
  }
}
