// This file is generated by SQG. Do not edit manually.
import type {
  DuckDBConnection,
  DuckDBMaterializedResult,
} from "@duckdb/node-api";

export class TestDuckdb {
  constructor(private conn: DuckDBConnection) {}

  static getMigrations(): string[] {
    return [
      `CREATE SEQUENCE seq_users_id START 1;

create table if not exists users (
    id integer primary key not null default nextval('seq_users_id'),
    name text not null,
    email text not null unique
);


create table if not exists actions (
    id integer primary key not null,
    action text not null,
    value double,
    user_id integer not null references users(id),
    timestamp integer not null
);`,
    ];
  }

  static getQueryNames(): Map<string, keyof TestDuckdb> {
    return new Map([
      ["insert", "insert"],
      ["all", "all"],
      ["all_emails", "allEmails"],
      ["by_id", "byId"],
      ["by_email", "byEmail"],
      ["get_id_by_email", "getIdByEmail"],
      ["update_email", "updateEmail"],
      ["delete", "delete"],
      ["actions_by_user_id", "actionsByUserId"],
      ["actions_by_user_id_and_action", "actionsByUserIdAndAction"],
      ["top_users", "topUsers"],
      ["test", "test"],
      ["test2", "test2"],
      ["test3", "test3"],
      ["test4", "test4"],
      ["test5", "test5"],
      ["testList", "testList"],
      ["testList2", "testList2"],
      ["testList3", "testList3"],
      ["testMap", "testMap"],
      ["testMap2", "testMap2"],
      ["testMap3", "testMap3"],
      ["testStruct", "testStruct"],
      ["testStruct2", "testStruct2"],
      ["testStruct3", "testStruct3"],
      ["testStruct4", "testStruct4"],
      ["testNestedStructs", "testNestedStructs"],
      ["testNested", "testNested"],
      ["testNested2", "testNested2"],
      ["testNested3", "testNested3"],
      ["test_all_types", "testAllTypes"],
    ]);
  }

  async insert(name: string, email: string): Promise<DuckDBMaterializedResult> {
    const sql = "insert into users (name, email) values ( ?, ?);";
    return await this.conn.run(sql, [name, email]);
  }

  async all(): Promise<
    {
      a: string | null;
      x: number | null;
      id: number | null;
      name: string | null;
      email: string | null;
    }[]
  > {
    const sql = `select 'abc' as a,1 as x,* from users;`;
    const reader = await this.conn.runAndReadAll(sql, []);
    return reader.getRowObjects() as {
      a: string | null;
      x: number | null;
      id: number | null;
      name: string | null;
      email: string | null;
    }[];
  }

  async allEmails(): Promise<(string | null)[]> {
    const sql = "select email from users;";
    const reader = await this.conn.runAndReadAll(sql, []);
    return reader.getRows().map((row) => row[0] as string | null);
  }

  async byId(
    id: number,
  ): Promise<
    { id: number | null; name: string | null; email: string | null } | undefined
  > {
    const sql = "select * from users where id =? limit 1;";
    const reader = await this.conn.runAndReadAll(sql, [id]);
    return reader.getRowObjects()[0] as
      | { id: number | null; name: string | null; email: string | null }
      | undefined;
  }

  async byEmail(
    email: string,
  ): Promise<
    { id: number | null; name: string | null; email: string | null } | undefined
  > {
    const sql = "select * from users where email =?;";
    const reader = await this.conn.runAndReadAll(sql, [email]);
    return reader.getRowObjects()[0] as
      | { id: number | null; name: string | null; email: string | null }
      | undefined;
  }

  async getIdByEmail(email: string): Promise<number | null | undefined> {
    const sql = "select id from users where email =?;";
    const reader = await this.conn.runAndReadAll(sql, [email]);
    return reader.getRows()[0]?.[0] as number | null | undefined;
  }

  async updateEmail(
    id: number,
    email: string,
  ): Promise<DuckDBMaterializedResult> {
    const sql = "update users set email =? where id =?;";
    return await this.conn.run(sql, [email, id]);
  }

  async delete(id: number): Promise<DuckDBMaterializedResult> {
    const sql = "delete from users where id =?;";
    return await this.conn.run(sql, [id]);
  }

  async actionsByUserId(
    user_id: number,
  ): Promise<
    {
      id: number | null;
      action: string | null;
      value: number | null;
      user_id: number | null;
      timestamp: number | null;
    }[]
  > {
    const sql = "select * from actions where user_id =?;";
    const reader = await this.conn.runAndReadAll(sql, [user_id]);
    return reader.getRowObjects() as {
      id: number | null;
      action: string | null;
      value: number | null;
      user_id: number | null;
      timestamp: number | null;
    }[];
  }

  async actionsByUserIdAndAction(
    user_id: number,
    action: string,
  ): Promise<
    {
      id: number | null;
      action: string | null;
      value: number | null;
      user_id: number | null;
      timestamp: number | null;
    }[]
  > {
    const sql = `select * from actions 
 
  where user_id =? and action =?;

 `;
    const reader = await this.conn.runAndReadAll(sql, [user_id, action]);
    return reader.getRowObjects() as {
      id: number | null;
      action: string | null;
      value: number | null;
      user_id: number | null;
      timestamp: number | null;
    }[];
  }

  async topUsers(): Promise<
    { user_id: number | null; total_value: number | null }[]
  > {
    const sql =
      "SELECT user_id, SUM(value) as total_value FROM actions GROUP BY user_id ORDER BY total_value DESC LIMIT 10;";
    const reader = await this.conn.runAndReadAll(sql, []);
    return reader.getRowObjects() as {
      user_id: number | null;
      total_value: number | null;
    }[];
  }

  async test(a: number): Promise<{ n: number | null }[]> {
    const sql = "select 1 as n where ? ::int is null; ";
    const reader = await this.conn.runAndReadAll(sql, [a]);
    return reader.getRowObjects() as { n: number | null }[];
  }

  async test2(): Promise<{ n: number | null }[]> {
    const sql = "select  1 as n;";
    const reader = await this.conn.runAndReadAll(sql, []);
    return reader.getRowObjects() as { n: number | null }[];
  }

  async test3(): Promise<{ b: string | null; a: number | null }[]> {
    const sql = `select '--ok' b,2 as a `;
    const reader = await this.conn.runAndReadAll(sql, []);
    return reader.getRowObjects() as { b: string | null; a: number | null }[];
  }

  async test4(): Promise<{ s: string | null; z: number | null }[]> {
    const sql = `select '/* lol */' s , 5 as z`;
    const reader = await this.conn.runAndReadAll(sql, []);
    return reader.getRowObjects() as { s: string | null; z: number | null }[];
  }

  async test5(): Promise<
    { x: string | null; y: string | null; c: number | null }[]
  > {
    const sql = `select 'a 	' x , 'a	 a' y, 1 as c`;
    const reader = await this.conn.runAndReadAll(sql, []);
    return reader.getRowObjects() as {
      x: string | null;
      y: string | null;
      c: number | null;
    }[];
  }

  async testList(): Promise<{ names: { items: (string | null)[] } }[]> {
    const sql = `select ['a','b', 'c'] as names`;
    const reader = await this.conn.runAndReadAll(sql, []);
    return reader.getRowObjects() as { names: { items: (string | null)[] } }[];
  }

  async testList2(): Promise<{ items: (string | null)[] }[]> {
    const sql = `select ['a','b', 'c'] as names`;
    const reader = await this.conn.runAndReadAll(sql, []);
    return reader
      .getRows()
      .map((row) => row[0] as { items: (string | null)[] });
  }

  async testList3(): Promise<{ items: (string | null)[] } | undefined> {
    const sql = `select ['a','b', 'c'] as names`;
    const reader = await this.conn.runAndReadAll(sql, []);
    return reader.getRows()[0]?.[0] as { items: (string | null)[] } | undefined;
  }

  async testMap(): Promise<
    { props: { entries: { key: string | null; value: number | null }[] } }[]
  > {
    const sql = `select props: MAP {'a' : 1}`;
    const reader = await this.conn.runAndReadAll(sql, []);
    return reader.getRowObjects() as {
      props: { entries: { key: string | null; value: number | null }[] };
    }[];
  }

  async testMap2(): Promise<
    { props: { entries: { key: number | null; value: number | null }[] } }[]
  > {
    const sql = ` 
select props: MAP { 1 : 2 }`;
    const reader = await this.conn.runAndReadAll(sql, []);
    return reader.getRowObjects() as {
      props: { entries: { key: number | null; value: number | null }[] };
    }[];
  }

  async testMap3(): Promise<
    {
      props: {
        entries: { key: { items: (number | null)[] }; value: number | null }[];
      };
    }[]
  > {
    const sql = ` 
select props: MAP { [1] : 2 }`;
    const reader = await this.conn.runAndReadAll(sql, []);
    return reader.getRowObjects() as {
      props: {
        entries: { key: { items: (number | null)[] }; value: number | null }[];
      };
    }[];
  }

  async testStruct(): Promise<
    {
      data: {
        entries: {
          test: number | null;
          name: string | null;
          nested: { entries: { test: boolean | null } };
        };
      };
    }[]
  > {
    const sql = `select data: {'test' : 1, 'name' : 'abc', 'nested' : {'test' : true}}`;
    const reader = await this.conn.runAndReadAll(sql, []);
    return reader.getRowObjects() as {
      data: {
        entries: {
          test: number | null;
          name: string | null;
          nested: { entries: { test: boolean | null } };
        };
      };
    }[];
  }

  async testStruct2(): Promise<
    {
      entries: {
        test: number | null;
        name: string | null;
        nested: { entries: { test: boolean | null } };
      };
    }[]
  > {
    const sql = `select data: {'test' : 1, 'name' : 'abc', 'nested' : {'test' : true}}`;
    const reader = await this.conn.runAndReadAll(sql, []);
    return reader
      .getRows()
      .map(
        (row) =>
          row[0] as {
            entries: {
              test: number | null;
              name: string | null;
              nested: { entries: { test: boolean | null } };
            };
          },
      );
  }

  async testStruct3(): Promise<
    | {
        entries: {
          test: number | null;
          name: string | null;
          nested: { entries: { test: boolean | null } };
        };
      }
    | undefined
  > {
    const sql = `select data: {'test' : 1, 'name' : 'abc', 'nested' : {'test' : true}}`;
    const reader = await this.conn.runAndReadAll(sql, []);
    return reader.getRows()[0]?.[0] as
      | {
          entries: {
            test: number | null;
            name: string | null;
            nested: { entries: { test: boolean | null } };
          };
        }
      | undefined;
  }

  async testStruct4(): Promise<
    | {
        data: {
          entries: {
            test: number | null;
            name: string | null;
            nested: { entries: { test: boolean | null } };
          };
        };
      }
    | undefined
  > {
    const sql = `select data: {'test' : 1, 'name' : 'abc', 'nested' : {'test' : true}}`;
    const reader = await this.conn.runAndReadAll(sql, []);
    return reader.getRowObjects()[0] as
      | {
          data: {
            entries: {
              test: number | null;
              name: string | null;
              nested: { entries: { test: boolean | null } };
            };
          };
        }
      | undefined;
  }

  async testNestedStructs(): Promise<
    | {
        data: {
          entries: {
            v: number | null;
            x: {
              entries: {
                v: number | null;
                y: {
                  entries: {
                    v: number | null;
                    z: { items: (number | null)[] };
                  };
                };
              };
            };
          };
        };
      }
    | undefined
  > {
    const sql = `select {v:1,'x' : {v:2,'y' : {v:3, 'z' : [1]}}} as data`;
    const reader = await this.conn.runAndReadAll(sql, []);
    return reader.getRowObjects()[0] as
      | {
          data: {
            entries: {
              v: number | null;
              x: {
                entries: {
                  v: number | null;
                  y: {
                    entries: {
                      v: number | null;
                      z: { items: (number | null)[] };
                    };
                  };
                };
              };
            };
          };
        }
      | undefined;
  }

  async testNested(): Promise<
    {
      data: {
        entries: {
          key: string | null;
          value: { items: { entries: { a: number | null } }[] };
        }[];
      };
    }[]
  > {
    const sql = `select MAP {'x' : [{'a' : 1}]} as data`;
    const reader = await this.conn.runAndReadAll(sql, []);
    return reader.getRowObjects() as {
      data: {
        entries: {
          key: string | null;
          value: { items: { entries: { a: number | null } }[] };
        }[];
      };
    }[];
  }

  async testNested2(): Promise<
    | {
        data: {
          entries: { x: { items: { entries: { a: number | null } }[] } };
        };
      }
    | undefined
  > {
    const sql = `select {'x' : [{'a' : 1}]} as data
 `;
    const reader = await this.conn.runAndReadAll(sql, []);
    return reader.getRowObjects()[0] as
      | {
          data: {
            entries: { x: { items: { entries: { a: number | null } }[] } };
          };
        }
      | undefined;
  }

  async testNested3(): Promise<
    | {
        a: { items: (number | null)[] };
        b: number | null;
        c: {
          entries: {
            x: { items: { entries: { a: number | null } }[] };
            y: { entries: { z: number | null } };
          };
        };
      }
    | undefined
  > {
    const sql = `select a:[1,2,3] ,b:2, c: {'x' : [{'a' : 1}], 'y' : {'z' : 3}}


 
 


 
 `;
    const reader = await this.conn.runAndReadAll(sql, []);
    return reader.getRowObjects()[0] as
      | {
          a: { items: (number | null)[] };
          b: number | null;
          c: {
            entries: {
              x: { items: { entries: { a: number | null } }[] };
              y: { entries: { z: number | null } };
            };
          };
        }
      | undefined;
  }

  async testAllTypes(): Promise<
    {
      bool: boolean | null;
      tinyint: number | null;
      smallint: number | null;
      int: number | null;
      bigint: bigint | null;
      hugeint: bigint | null;
      uhugeint: bigint | null;
      utinyint: number | null;
      usmallint: number | null;
      uint: number | null;
      ubigint: bigint | null;
      bignum: bigint | null;
      date: { days: number } | null;
      time: { micros: bigint } | null;
      timestamp: { micros: bigint } | null;
      timestamp_s: { seconds: bigint } | null;
      timestamp_ms: { millis: bigint } | null;
      timestamp_ns: { nanos: bigint } | null;
      time_tz: { micros: bigint; offset: number } | null;
      timestamp_tz: { micros: bigint } | null;
      float: number | null;
      double: number | null;
      dec_4_1: { width: number; scale: number; value: bigint } | null;
      dec_9_4: { width: number; scale: number; value: bigint } | null;
      dec_18_6: { width: number; scale: number; value: bigint } | null;
      dec38_10: { width: number; scale: number; value: bigint } | null;
      uuid: { hugeint: bigint } | null;
      interval: { months: number; days: number; micros: bigint } | null;
      varchar: string | null;
      blob: { bytes: Uint8Array } | null;
      bit: { data: Uint8Array } | null;
      small_enum: "DUCK_DUCK_ENUM" | "GOOSE" | null;
      medium_enum:
        | "enum_0"
        | "enum_1"
        | "enum_2"
        | "enum_3"
        | "enum_4"
        | "enum_5"
        | "enum_6"
        | "enum_7"
        | "enum_8"
        | "enum_9"
        | "enum_10"
        | "enum_11"
        | "enum_12"
        | "enum_13"
        | "enum_14"
        | "enum_15"
        | "enum_16"
        | "enum_17"
        | "enum_18"
        | "enum_19"
        | "enum_20"
        | "enum_21"
        | "enum_22"
        | "enum_23"
        | "enum_24"
        | "enum_25"
        | "enum_26"
        | "enum_27"
        | "enum_28"
        | "enum_29"
        | "enum_30"
        | "enum_31"
        | "enum_32"
        | "enum_33"
        | "enum_34"
        | "enum_35"
        | "enum_36"
        | "enum_37"
        | "enum_38"
        | "enum_39"
        | "enum_40"
        | "enum_41"
        | "enum_42"
        | "enum_43"
        | "enum_44"
        | "enum_45"
        | "enum_46"
        | "enum_47"
        | "enum_48"
        | "enum_49"
        | "enum_50"
        | "enum_51"
        | "enum_52"
        | "enum_53"
        | "enum_54"
        | "enum_55"
        | "enum_56"
        | "enum_57"
        | "enum_58"
        | "enum_59"
        | "enum_60"
        | "enum_61"
        | "enum_62"
        | "enum_63"
        | "enum_64"
        | "enum_65"
        | "enum_66"
        | "enum_67"
        | "enum_68"
        | "enum_69"
        | "enum_70"
        | "enum_71"
        | "enum_72"
        | "enum_73"
        | "enum_74"
        | "enum_75"
        | "enum_76"
        | "enum_77"
        | "enum_78"
        | "enum_79"
        | "enum_80"
        | "enum_81"
        | "enum_82"
        | "enum_83"
        | "enum_84"
        | "enum_85"
        | "enum_86"
        | "enum_87"
        | "enum_88"
        | "enum_89"
        | "enum_90"
        | "enum_91"
        | "enum_92"
        | "enum_93"
        | "enum_94"
        | "enum_95"
        | "enum_96"
        | "enum_97"
        | "enum_98"
        | "enum_99"
        | "enum_100"
        | "enum_101"
        | "enum_102"
        | "enum_103"
        | "enum_104"
        | "enum_105"
        | "enum_106"
        | "enum_107"
        | "enum_108"
        | "enum_109"
        | "enum_110"
        | "enum_111"
        | "enum_112"
        | "enum_113"
        | "enum_114"
        | "enum_115"
        | "enum_116"
        | "enum_117"
        | "enum_118"
        | "enum_119"
        | "enum_120"
        | "enum_121"
        | "enum_122"
        | "enum_123"
        | "enum_124"
        | "enum_125"
        | "enum_126"
        | "enum_127"
        | "enum_128"
        | "enum_129"
        | "enum_130"
        | "enum_131"
        | "enum_132"
        | "enum_133"
        | "enum_134"
        | "enum_135"
        | "enum_136"
        | "enum_137"
        | "enum_138"
        | "enum_139"
        | "enum_140"
        | "enum_141"
        | "enum_142"
        | "enum_143"
        | "enum_144"
        | "enum_145"
        | "enum_146"
        | "enum_147"
        | "enum_148"
        | "enum_149"
        | "enum_150"
        | "enum_151"
        | "enum_152"
        | "enum_153"
        | "enum_154"
        | "enum_155"
        | "enum_156"
        | "enum_157"
        | "enum_158"
        | "enum_159"
        | "enum_160"
        | "enum_161"
        | "enum_162"
        | "enum_163"
        | "enum_164"
        | "enum_165"
        | "enum_166"
        | "enum_167"
        | "enum_168"
        | "enum_169"
        | "enum_170"
        | "enum_171"
        | "enum_172"
        | "enum_173"
        | "enum_174"
        | "enum_175"
        | "enum_176"
        | "enum_177"
        | "enum_178"
        | "enum_179"
        | "enum_180"
        | "enum_181"
        | "enum_182"
        | "enum_183"
        | "enum_184"
        | "enum_185"
        | "enum_186"
        | "enum_187"
        | "enum_188"
        | "enum_189"
        | "enum_190"
        | "enum_191"
        | "enum_192"
        | "enum_193"
        | "enum_194"
        | "enum_195"
        | "enum_196"
        | "enum_197"
        | "enum_198"
        | "enum_199"
        | "enum_200"
        | "enum_201"
        | "enum_202"
        | "enum_203"
        | "enum_204"
        | "enum_205"
        | "enum_206"
        | "enum_207"
        | "enum_208"
        | "enum_209"
        | "enum_210"
        | "enum_211"
        | "enum_212"
        | "enum_213"
        | "enum_214"
        | "enum_215"
        | "enum_216"
        | "enum_217"
        | "enum_218"
        | "enum_219"
        | "enum_220"
        | "enum_221"
        | "enum_222"
        | "enum_223"
        | "enum_224"
        | "enum_225"
        | "enum_226"
        | "enum_227"
        | "enum_228"
        | "enum_229"
        | "enum_230"
        | "enum_231"
        | "enum_232"
        | "enum_233"
        | "enum_234"
        | "enum_235"
        | "enum_236"
        | "enum_237"
        | "enum_238"
        | "enum_239"
        | "enum_240"
        | "enum_241"
        | "enum_242"
        | "enum_243"
        | "enum_244"
        | "enum_245"
        | "enum_246"
        | "enum_247"
        | "enum_248"
        | "enum_249"
        | "enum_250"
        | "enum_251"
        | "enum_252"
        | "enum_253"
        | "enum_254"
        | "enum_255"
        | "enum_256"
        | "enum_257"
        | "enum_258"
        | "enum_259"
        | "enum_260"
        | "enum_261"
        | "enum_262"
        | "enum_263"
        | "enum_264"
        | "enum_265"
        | "enum_266"
        | "enum_267"
        | "enum_268"
        | "enum_269"
        | "enum_270"
        | "enum_271"
        | "enum_272"
        | "enum_273"
        | "enum_274"
        | "enum_275"
        | "enum_276"
        | "enum_277"
        | "enum_278"
        | "enum_279"
        | "enum_280"
        | "enum_281"
        | "enum_282"
        | "enum_283"
        | "enum_284"
        | "enum_285"
        | "enum_286"
        | "enum_287"
        | "enum_288"
        | "enum_289"
        | "enum_290"
        | "enum_291"
        | "enum_292"
        | "enum_293"
        | "enum_294"
        | "enum_295"
        | "enum_296"
        | "enum_297"
        | "enum_298"
        | "enum_299"
        | null;
      large_enum: "enum_0" | "enum_69999" | null;
      int_array: { items: (number | null)[] };
      double_array: { items: (number | null)[] };
      date_array: { items: ({ days: number } | null)[] };
      timestamp_array: { items: ({ micros: bigint } | null)[] };
      timestamptz_array: { items: ({ micros: bigint } | null)[] };
      varchar_array: { items: (string | null)[] };
      nested_int_array: { items: { items: (number | null)[] }[] };
      struct: { entries: { a: number | null; b: string | null } };
      struct_of_arrays: {
        entries: {
          a: { items: (number | null)[] };
          b: { items: (string | null)[] };
        };
      };
      array_of_structs: {
        items: { entries: { a: number | null; b: string | null } }[];
      };
      map: { entries: { key: string | null; value: string | null }[] };
      union: { tag: string; value: unknown } | null;
      fixed_int_array: { items: (number | null)[] } | null;
      fixed_varchar_array: { items: (string | null)[] } | null;
      fixed_nested_int_array: {
        items: ({ items: (number | null)[] } | null)[];
      } | null;
      fixed_nested_varchar_array: {
        items: ({ items: (string | null)[] } | null)[];
      } | null;
      fixed_struct_array: { items: unknown[] };
      struct_of_fixed_array: {
        entries: {
          a: { items: (number | null)[] } | null;
          b: { items: (string | null)[] } | null;
        };
      };
      fixed_array_of_int_list: { items: unknown[] };
      list_of_fixed_int_array: {
        items: ({ items: (number | null)[] } | null)[];
      };
    }[]
  > {
    const sql = ` 
select * from test_all_types();`;
    const reader = await this.conn.runAndReadAll(sql, []);
    return reader.getRowObjects() as {
      bool: boolean | null;
      tinyint: number | null;
      smallint: number | null;
      int: number | null;
      bigint: bigint | null;
      hugeint: bigint | null;
      uhugeint: bigint | null;
      utinyint: number | null;
      usmallint: number | null;
      uint: number | null;
      ubigint: bigint | null;
      bignum: bigint | null;
      date: { days: number } | null;
      time: { micros: bigint } | null;
      timestamp: { micros: bigint } | null;
      timestamp_s: { seconds: bigint } | null;
      timestamp_ms: { millis: bigint } | null;
      timestamp_ns: { nanos: bigint } | null;
      time_tz: { micros: bigint; offset: number } | null;
      timestamp_tz: { micros: bigint } | null;
      float: number | null;
      double: number | null;
      dec_4_1: { width: number; scale: number; value: bigint } | null;
      dec_9_4: { width: number; scale: number; value: bigint } | null;
      dec_18_6: { width: number; scale: number; value: bigint } | null;
      dec38_10: { width: number; scale: number; value: bigint } | null;
      uuid: { hugeint: bigint } | null;
      interval: { months: number; days: number; micros: bigint } | null;
      varchar: string | null;
      blob: { bytes: Uint8Array } | null;
      bit: { data: Uint8Array } | null;
      small_enum: "DUCK_DUCK_ENUM" | "GOOSE" | null;
      medium_enum:
        | "enum_0"
        | "enum_1"
        | "enum_2"
        | "enum_3"
        | "enum_4"
        | "enum_5"
        | "enum_6"
        | "enum_7"
        | "enum_8"
        | "enum_9"
        | "enum_10"
        | "enum_11"
        | "enum_12"
        | "enum_13"
        | "enum_14"
        | "enum_15"
        | "enum_16"
        | "enum_17"
        | "enum_18"
        | "enum_19"
        | "enum_20"
        | "enum_21"
        | "enum_22"
        | "enum_23"
        | "enum_24"
        | "enum_25"
        | "enum_26"
        | "enum_27"
        | "enum_28"
        | "enum_29"
        | "enum_30"
        | "enum_31"
        | "enum_32"
        | "enum_33"
        | "enum_34"
        | "enum_35"
        | "enum_36"
        | "enum_37"
        | "enum_38"
        | "enum_39"
        | "enum_40"
        | "enum_41"
        | "enum_42"
        | "enum_43"
        | "enum_44"
        | "enum_45"
        | "enum_46"
        | "enum_47"
        | "enum_48"
        | "enum_49"
        | "enum_50"
        | "enum_51"
        | "enum_52"
        | "enum_53"
        | "enum_54"
        | "enum_55"
        | "enum_56"
        | "enum_57"
        | "enum_58"
        | "enum_59"
        | "enum_60"
        | "enum_61"
        | "enum_62"
        | "enum_63"
        | "enum_64"
        | "enum_65"
        | "enum_66"
        | "enum_67"
        | "enum_68"
        | "enum_69"
        | "enum_70"
        | "enum_71"
        | "enum_72"
        | "enum_73"
        | "enum_74"
        | "enum_75"
        | "enum_76"
        | "enum_77"
        | "enum_78"
        | "enum_79"
        | "enum_80"
        | "enum_81"
        | "enum_82"
        | "enum_83"
        | "enum_84"
        | "enum_85"
        | "enum_86"
        | "enum_87"
        | "enum_88"
        | "enum_89"
        | "enum_90"
        | "enum_91"
        | "enum_92"
        | "enum_93"
        | "enum_94"
        | "enum_95"
        | "enum_96"
        | "enum_97"
        | "enum_98"
        | "enum_99"
        | "enum_100"
        | "enum_101"
        | "enum_102"
        | "enum_103"
        | "enum_104"
        | "enum_105"
        | "enum_106"
        | "enum_107"
        | "enum_108"
        | "enum_109"
        | "enum_110"
        | "enum_111"
        | "enum_112"
        | "enum_113"
        | "enum_114"
        | "enum_115"
        | "enum_116"
        | "enum_117"
        | "enum_118"
        | "enum_119"
        | "enum_120"
        | "enum_121"
        | "enum_122"
        | "enum_123"
        | "enum_124"
        | "enum_125"
        | "enum_126"
        | "enum_127"
        | "enum_128"
        | "enum_129"
        | "enum_130"
        | "enum_131"
        | "enum_132"
        | "enum_133"
        | "enum_134"
        | "enum_135"
        | "enum_136"
        | "enum_137"
        | "enum_138"
        | "enum_139"
        | "enum_140"
        | "enum_141"
        | "enum_142"
        | "enum_143"
        | "enum_144"
        | "enum_145"
        | "enum_146"
        | "enum_147"
        | "enum_148"
        | "enum_149"
        | "enum_150"
        | "enum_151"
        | "enum_152"
        | "enum_153"
        | "enum_154"
        | "enum_155"
        | "enum_156"
        | "enum_157"
        | "enum_158"
        | "enum_159"
        | "enum_160"
        | "enum_161"
        | "enum_162"
        | "enum_163"
        | "enum_164"
        | "enum_165"
        | "enum_166"
        | "enum_167"
        | "enum_168"
        | "enum_169"
        | "enum_170"
        | "enum_171"
        | "enum_172"
        | "enum_173"
        | "enum_174"
        | "enum_175"
        | "enum_176"
        | "enum_177"
        | "enum_178"
        | "enum_179"
        | "enum_180"
        | "enum_181"
        | "enum_182"
        | "enum_183"
        | "enum_184"
        | "enum_185"
        | "enum_186"
        | "enum_187"
        | "enum_188"
        | "enum_189"
        | "enum_190"
        | "enum_191"
        | "enum_192"
        | "enum_193"
        | "enum_194"
        | "enum_195"
        | "enum_196"
        | "enum_197"
        | "enum_198"
        | "enum_199"
        | "enum_200"
        | "enum_201"
        | "enum_202"
        | "enum_203"
        | "enum_204"
        | "enum_205"
        | "enum_206"
        | "enum_207"
        | "enum_208"
        | "enum_209"
        | "enum_210"
        | "enum_211"
        | "enum_212"
        | "enum_213"
        | "enum_214"
        | "enum_215"
        | "enum_216"
        | "enum_217"
        | "enum_218"
        | "enum_219"
        | "enum_220"
        | "enum_221"
        | "enum_222"
        | "enum_223"
        | "enum_224"
        | "enum_225"
        | "enum_226"
        | "enum_227"
        | "enum_228"
        | "enum_229"
        | "enum_230"
        | "enum_231"
        | "enum_232"
        | "enum_233"
        | "enum_234"
        | "enum_235"
        | "enum_236"
        | "enum_237"
        | "enum_238"
        | "enum_239"
        | "enum_240"
        | "enum_241"
        | "enum_242"
        | "enum_243"
        | "enum_244"
        | "enum_245"
        | "enum_246"
        | "enum_247"
        | "enum_248"
        | "enum_249"
        | "enum_250"
        | "enum_251"
        | "enum_252"
        | "enum_253"
        | "enum_254"
        | "enum_255"
        | "enum_256"
        | "enum_257"
        | "enum_258"
        | "enum_259"
        | "enum_260"
        | "enum_261"
        | "enum_262"
        | "enum_263"
        | "enum_264"
        | "enum_265"
        | "enum_266"
        | "enum_267"
        | "enum_268"
        | "enum_269"
        | "enum_270"
        | "enum_271"
        | "enum_272"
        | "enum_273"
        | "enum_274"
        | "enum_275"
        | "enum_276"
        | "enum_277"
        | "enum_278"
        | "enum_279"
        | "enum_280"
        | "enum_281"
        | "enum_282"
        | "enum_283"
        | "enum_284"
        | "enum_285"
        | "enum_286"
        | "enum_287"
        | "enum_288"
        | "enum_289"
        | "enum_290"
        | "enum_291"
        | "enum_292"
        | "enum_293"
        | "enum_294"
        | "enum_295"
        | "enum_296"
        | "enum_297"
        | "enum_298"
        | "enum_299"
        | null;
      large_enum: "enum_0" | "enum_69999" | null;
      int_array: { items: (number | null)[] };
      double_array: { items: (number | null)[] };
      date_array: { items: ({ days: number } | null)[] };
      timestamp_array: { items: ({ micros: bigint } | null)[] };
      timestamptz_array: { items: ({ micros: bigint } | null)[] };
      varchar_array: { items: (string | null)[] };
      nested_int_array: { items: { items: (number | null)[] }[] };
      struct: { entries: { a: number | null; b: string | null } };
      struct_of_arrays: {
        entries: {
          a: { items: (number | null)[] };
          b: { items: (string | null)[] };
        };
      };
      array_of_structs: {
        items: { entries: { a: number | null; b: string | null } }[];
      };
      map: { entries: { key: string | null; value: string | null }[] };
      union: { tag: string; value: unknown } | null;
      fixed_int_array: { items: (number | null)[] } | null;
      fixed_varchar_array: { items: (string | null)[] } | null;
      fixed_nested_int_array: {
        items: ({ items: (number | null)[] } | null)[];
      } | null;
      fixed_nested_varchar_array: {
        items: ({ items: (string | null)[] } | null)[];
      } | null;
      fixed_struct_array: { items: unknown[] };
      struct_of_fixed_array: {
        entries: {
          a: { items: (number | null)[] } | null;
          b: { items: (string | null)[] } | null;
        };
      };
      fixed_array_of_int_list: { items: unknown[] };
      list_of_fixed_int_array: {
        items: ({ items: (number | null)[] } | null)[];
      };
    }[];
  }
}
