// This file is generated by SQG (https://sqg.dev). Do not edit manually.
package sqg.generated;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.sql.Array;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Struct;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.OffsetDateTime;
import java.time.OffsetTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.NoSuchElementException;
import java.util.Spliterator;
import java.util.Spliterators;
import java.util.UUID;
import java.util.function.Function;
import java.util.stream.Stream;
import java.util.stream.StreamSupport;

public class TestParamTypes {

    private final Connection connection;

    public TestParamTypes(Connection connection) {
        this.connection = connection;
    }

    /** Options for streaming queries. fetchSize hints at the JDBC driver's batch size; 0 means driver default. */
    public record StreamOptions(int fetchSize) {
        public static final StreamOptions DEFAULT = new StreamOptions(0);

        public StreamOptions withFetchSize(int fetchSize) {
            return new StreamOptions(fetchSize);
        }
    }

    private static Object[] getObjectArray(Array array) {
        if (array == null) {
            return null;
        }
        try {
            return (Object[]) array.getArray();
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    private static Object[] getAttr(Struct struct) {
        if (struct == null) {
            return null;
        }
        try {
            return struct.getAttributes();
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    private static LocalDateTime toLocalDateTime(Object ts) {
        if (ts == null) return null;
        if (ts instanceof LocalDateTime ldt) return ldt;
        return ((java.sql.Timestamp) ts).toLocalDateTime();
    }

    private static LocalDate toLocalDate(Object d) {
        if (d == null) return null;
        if (d instanceof LocalDate ld) return ld;
        return ((java.sql.Date) d).toLocalDate();
    }

    private static LocalTime toLocalTime(Object t) {
        if (t == null) return null;
        if (t instanceof LocalTime lt) return lt;
        return ((java.sql.Time) t).toLocalTime();
    }

    private static OffsetDateTime toOffsetDateTime(Object ts) {
        if (ts == null) return null;
        if (ts instanceof OffsetDateTime odt) return odt;
        return ((java.sql.Timestamp) ts).toInstant().atOffset(
            java.time.ZoneOffset.UTC
        );
    }

    private static <K> List<K> arrayToList(
        Array array,
        Class<? extends K[]> baseType
    ) {
        var objectArray = getObjectArray(array);
        if (objectArray == null) {
            return null;
        }
        return Collections.unmodifiableList(
            Arrays.asList(
                Arrays.copyOf(objectArray, objectArray.length, baseType)
            )
        );
    }

    private static <K> List<K> arrayOfStructToList(
        Array array,
        Function<Object[], K> convert
    ) {
        var objectArray = getObjectArray(array);
        if (objectArray == null) {
            return null;
        }
        var list = new ArrayList<K>(objectArray.length);
        for (Object obj : objectArray) {
            list.add(obj != null ? convert.apply(getAttr((Struct) obj)) : null);
        }
        return Collections.unmodifiableList(list);
    }

    @SuppressWarnings("unchecked")
    private static <K> List<List<K>> multiDimArrayToList(
        Array array,
        Class<? extends K[]> baseType
    ) {
        var objectArray = getObjectArray(array);
        if (objectArray == null) {
            return null;
        }
        var list = new ArrayList<List<K>>(objectArray.length);
        for (Object obj : objectArray) {
            if (obj == null) {
                list.add(null);
            } else if (obj instanceof Array) {
                list.add(arrayToList((Array) obj, baseType));
            } else if (obj instanceof Object[]) {
                var inner = (Object[]) obj;
                list.add(
                    Collections.unmodifiableList(
                        Arrays.asList(
                            Arrays.copyOf(inner, inner.length, baseType)
                        )
                    )
                );
            } else {
                throw new RuntimeException(
                    "Unexpected type in multi-dimensional array: " +
                        obj.getClass()
                );
            }
        }
        return Collections.unmodifiableList(list);
    }

    private static final List<String> migrations = List.of(
        """
        create table events(day date, n integer, label text, big bigint);"""
    );

    private static final List<String> migrationIds = List.of("1");

    public static List<String> getMigrations() {
        return migrations;
    }

    public static void applyMigrations(Connection connection)
        throws SQLException {
        applyMigrations(connection, "test-param-types");
    }

    public static void applyMigrations(
        Connection connection,
        String projectName
    ) throws SQLException {
        try (var stmt = connection.createStatement()) {
            stmt.execute(
                """
                CREATE TABLE IF NOT EXISTS _sqg_migrations (
                    project TEXT NOT NULL,
                    migration_id TEXT NOT NULL,
                    applied_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    PRIMARY KEY (project, migration_id)
                )"""
            );
        }
        boolean wasAutoCommit = connection.getAutoCommit();
        connection.setAutoCommit(false);
        try {
            var applied = new java.util.HashSet<String>();
            try (
                var stmt = connection.prepareStatement(
                    "SELECT migration_id FROM _sqg_migrations WHERE project = ?"
                )
            ) {
                stmt.setString(1, projectName);
                try (var rs = stmt.executeQuery()) {
                    while (rs.next()) {
                        applied.add(rs.getString(1));
                    }
                }
            }
            for (int i = 0; i < migrations.size(); i++) {
                var id = migrationIds.get(i);
                if (!applied.contains(id)) {
                    try (var stmt = connection.createStatement()) {
                        stmt.execute(migrations.get(i));
                    }
                    try (
                        var stmt = connection.prepareStatement(
                            "INSERT INTO _sqg_migrations (project, migration_id) VALUES (?, ?)"
                        )
                    ) {
                        stmt.setString(1, projectName);
                        stmt.setString(2, id);
                        stmt.executeUpdate();
                    }
                }
            }
            connection.commit();
        } catch (SQLException e) {
            connection.rollback();
            throw e;
        } finally {
            connection.setAutoCommit(wasAutoCommit);
        }
    }

    public int insertNullable(LocalDate day, String label, Long big)
        throws SQLException {
        try (
            var stmt = connection.prepareStatement(
                "insert into events(day, label, big) values (?::DATE, ?, ?);"
            )
        ) {
            stmt.setObject(1, day);
            stmt.setString(2, label);
            if (big != null) stmt.setLong(3, big);
            else stmt.setNull(3, java.sql.Types.BIGINT);

            return stmt.executeUpdate();
        }
    }

    public int ddlWithParam(Integer seed) throws SQLException {
        try (
            var stmt = connection.prepareStatement(
                "create or replace temp table tmp as select ? as a;"
            )
        ) {
            if (seed != null) stmt.setInt(1, seed);
            else stmt.setNull(1, java.sql.Types.INTEGER);

            return stmt.executeUpdate();
        }
    }

    public record CastMinusParamResult(Integer n) {}

    public List<CastMinusParamResult> castMinusParam(
        LocalDate since,
        Integer days
    ) throws SQLException {
        try (
            var stmt = connection.prepareStatement(
                "select n from events where day > (cast(? as DATE) - ?);"
            )
        ) {
            stmt.setObject(1, since);
            if (days != null) stmt.setInt(2, days);
            else stmt.setNull(2, java.sql.Types.INTEGER);

            try (var rs = stmt.executeQuery()) {
                var results = new ArrayList<CastMinusParamResult>();
                while (rs.next()) {
                    results.add(
                        new CastMinusParamResult(rs.getObject(1, Integer.class))
                    );
                }
                return results;
            }
        }
    }

    public Stream<CastMinusParamResult> castMinusParamStream(
        LocalDate since,
        Integer days
    ) throws SQLException {
        return castMinusParamStream(since, days, StreamOptions.DEFAULT);
    }

    public Stream<CastMinusParamResult> castMinusParamStream(
        LocalDate since,
        Integer days,
        StreamOptions options
    ) throws SQLException {
        var stmt = connection.prepareStatement(
            "select n from events where day > (cast(? as DATE) - ?);"
        );
        if (options.fetchSize() > 0) stmt.setFetchSize(options.fetchSize());
        stmt.setObject(1, since);
        if (days != null) stmt.setInt(2, days);
        else stmt.setNull(2, java.sql.Types.INTEGER);

        var rs = stmt.executeQuery();
        var iter = new Iterator<CastMinusParamResult>() {
            private Boolean hasNext = null;

            public boolean hasNext() {
                if (hasNext == null) {
                    try {
                        hasNext = rs.next();
                    } catch (SQLException e) {
                        throw new RuntimeException(e);
                    }
                }
                return hasNext;
            }

            public CastMinusParamResult next() {
                if (!hasNext()) throw new NoSuchElementException();
                hasNext = null;
                try {
                    return new CastMinusParamResult(
                        rs.getObject(1, Integer.class)
                    );
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        };
        return StreamSupport.stream(
            Spliterators.spliteratorUnknownSize(iter, Spliterator.ORDERED),
            false
        ).onClose(() -> {
            try {
                rs.close();
                stmt.close();
            } catch (SQLException e) {
                throw new RuntimeException(e);
            }
        });
    }

    public record StrptimeParamResult(Integer n) {}

    public List<StrptimeParamResult> strptimeParam(String since)
        throws SQLException {
        try (
            var stmt = connection.prepareStatement(
                "select n from events where day > strptime(?, '%Y-%m-%d');"
            )
        ) {
            stmt.setString(1, since);

            try (var rs = stmt.executeQuery()) {
                var results = new ArrayList<StrptimeParamResult>();
                while (rs.next()) {
                    results.add(
                        new StrptimeParamResult(rs.getObject(1, Integer.class))
                    );
                }
                return results;
            }
        }
    }

    public Stream<StrptimeParamResult> strptimeParamStream(String since)
        throws SQLException {
        return strptimeParamStream(since, StreamOptions.DEFAULT);
    }

    public Stream<StrptimeParamResult> strptimeParamStream(
        String since,
        StreamOptions options
    ) throws SQLException {
        var stmt = connection.prepareStatement(
            "select n from events where day > strptime(?, '%Y-%m-%d');"
        );
        if (options.fetchSize() > 0) stmt.setFetchSize(options.fetchSize());
        stmt.setString(1, since);

        var rs = stmt.executeQuery();
        var iter = new Iterator<StrptimeParamResult>() {
            private Boolean hasNext = null;

            public boolean hasNext() {
                if (hasNext == null) {
                    try {
                        hasNext = rs.next();
                    } catch (SQLException e) {
                        throw new RuntimeException(e);
                    }
                }
                return hasNext;
            }

            public StrptimeParamResult next() {
                if (!hasNext()) throw new NoSuchElementException();
                hasNext = null;
                try {
                    return new StrptimeParamResult(
                        rs.getObject(1, Integer.class)
                    );
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        };
        return StreamSupport.stream(
            Spliterators.spliteratorUnknownSize(iter, Spliterator.ORDERED),
            false
        ).onClose(() -> {
            try {
                rs.close();
                stmt.close();
            } catch (SQLException e) {
                throw new RuntimeException(e);
            }
        });
    }

    public record CastParamResult(Integer n) {}

    public List<CastParamResult> castParam(LocalDate since)
        throws SQLException {
        try (
            var stmt = connection.prepareStatement(
                "select n from events where day > cast(? as DATE);"
            )
        ) {
            stmt.setObject(1, since);

            try (var rs = stmt.executeQuery()) {
                var results = new ArrayList<CastParamResult>();
                while (rs.next()) {
                    results.add(
                        new CastParamResult(rs.getObject(1, Integer.class))
                    );
                }
                return results;
            }
        }
    }

    public Stream<CastParamResult> castParamStream(LocalDate since)
        throws SQLException {
        return castParamStream(since, StreamOptions.DEFAULT);
    }

    public Stream<CastParamResult> castParamStream(
        LocalDate since,
        StreamOptions options
    ) throws SQLException {
        var stmt = connection.prepareStatement(
            "select n from events where day > cast(? as DATE);"
        );
        if (options.fetchSize() > 0) stmt.setFetchSize(options.fetchSize());
        stmt.setObject(1, since);

        var rs = stmt.executeQuery();
        var iter = new Iterator<CastParamResult>() {
            private Boolean hasNext = null;

            public boolean hasNext() {
                if (hasNext == null) {
                    try {
                        hasNext = rs.next();
                    } catch (SQLException e) {
                        throw new RuntimeException(e);
                    }
                }
                return hasNext;
            }

            public CastParamResult next() {
                if (!hasNext()) throw new NoSuchElementException();
                hasNext = null;
                try {
                    return new CastParamResult(rs.getObject(1, Integer.class));
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        };
        return StreamSupport.stream(
            Spliterators.spliteratorUnknownSize(iter, Spliterator.ORDERED),
            false
        ).onClose(() -> {
            try {
                rs.close();
                stmt.close();
            } catch (SQLException e) {
                throw new RuntimeException(e);
            }
        });
    }
}
