// This file is generated by SQG (https://sqg.dev). Do not edit manually.
/* eslint-disable */
// biome-ignore-all lint: generated code
import { connect, type Database } from "@tursodatabase/database";

interface RunResult {
  changes: number;
  lastInsertRowid: number;
}

// Statement type inferred from Database.prepare()
type Statement = Awaited<ReturnType<Database["prepare"]>>;

export class TestSqlite {
  private statements = new Map<string, Statement>();

  constructor(private db: Database) {}

  private async prepare(id: string, query: string): Promise<Statement> {
    let stmt = this.statements.get(id);
    if (!stmt) {
      stmt = await this.db.prepare(query);
      this.statements.set(id, stmt);
    }
    return stmt;
  }

  static getMigrations(): string[] {
    return [
      `create table  users (
    id text primary key,
    name text not null,
    email text unique
) strict;`,
      `create table bigints (
  id integer primary key,
  posts bigint,
  total bigint not null
);`,
    ];
  }

  static async applyMigrations(
    db: Database,
    projectName = "test-turso",
  ): Promise<void> {
    const createStmt = db.prepare(`CREATE TABLE IF NOT EXISTS _sqg_migrations (
            project TEXT NOT NULL,
            migration_id TEXT NOT NULL,
            applied_at TEXT NOT NULL DEFAULT (datetime('now')),
            PRIMARY KEY (project, migration_id)
        )`);
    await createStmt.run();
    const selectStmt = db.prepare(
      "SELECT migration_id FROM _sqg_migrations WHERE project = ?",
    );
    const rows = (await selectStmt.all(projectName)) as {
      migration_id: string;
    }[];
    const applied = new Set(rows.map((r) => r.migration_id));
    const migrations: [string, string][] = [
      [
        "1",
        `create table  users (
    id text primary key,
    name text not null,
    email text unique
) strict;`,
      ],
      [
        "2",
        `create table bigints (
  id integer primary key,
  posts bigint,
  total bigint not null
);`,
      ],
    ];
    const applyFn = db.transaction(async () => {
      for (const [id, sql] of migrations) {
        if (!applied.has(id)) {
          const execStmt = db.prepare(sql);
          await execStmt.run();
          const insertStmt = db.prepare(
            "INSERT INTO _sqg_migrations (project, migration_id) VALUES (?, ?)",
          );
          await insertStmt.run(projectName, id);
        }
      }
    });
    await applyFn();
  }

  static getQueryNames(): Map<string, keyof TestSqlite> {
    return new Map([
      ["users1", "users1"],
      ["users2", "users2"],
      ["users3", "users3"],
      ["allEmails", "allEmails"],
      ["existsAny", "existsAny"],
      ["countAll", "countAll"],
      ["castSum", "castSum"],
      ["existsNoSemi", "existsNoSemi"],
      ["countTrailingWs", "countTrailingWs"],
      ["getBigints", "getBigints"],
      ["users4", "users4"],
      ["users5", "users5"],
      ["users6", "users6"],
      ["users7", "users7"],
      ["reserved_word_test", "reservedWordTest"],
    ]);
  }

  async users1(): Promise<
    { id: string; name: string; email: string | null }[]
  > {
    const stmt = await this.prepare("users1", "select * from users;");
    return (await stmt.all()) as {
      id: string;
      name: string;
      email: string | null;
    }[];
  }
  async users2(): Promise<string | undefined> {
    const stmt = await this.prepare(
      "users2",
      `select id from users where id = '1';`,
    );
    const row = (await stmt.get()) as Record<string, string> | undefined;
    return row ? Object.values(row)[0] : undefined;
  }
  async users3(): Promise<string | undefined> {
    const stmt = await this.prepare(
      "users3",
      `select name from users where id = '1';`,
    );
    const row = (await stmt.get()) as Record<string, string> | undefined;
    return row ? Object.values(row)[0] : undefined;
  }
  async allEmails(): Promise<(string | null)[]> {
    const stmt = await this.prepare("allEmails", "select email from users;");
    const rows = (await stmt.all()) as Record<string, string | null>[];
    return rows.map((row) => Object.values(row)[0]);
  }
  async existsAny(): Promise<number | undefined> {
    const stmt = await this.prepare(
      "existsAny",
      `select exists(select 1 from users where id = '1');`,
    );
    const row = (await stmt.get()) as Record<string, number> | undefined;
    return row ? Object.values(row)[0] : undefined;
  }
  async countAll(): Promise<number | undefined> {
    const stmt = await this.prepare("countAll", "select count(*) from users;");
    const row = (await stmt.get()) as Record<string, number> | undefined;
    return row ? Object.values(row)[0] : undefined;
  }
  async castSum(): Promise<number | undefined> {
    const stmt = await this.prepare(
      "castSum",
      `select cast(count(*) as integer) as n from users where id = '1';`,
    );
    const row = (await stmt.get()) as Record<string, number> | undefined;
    return row ? Object.values(row)[0] : undefined;
  }
  async existsNoSemi(): Promise<number | undefined> {
    const stmt = await this.prepare(
      "existsNoSemi",
      `select exists(select 1 from users where id = '1')`,
    );
    const row = (await stmt.get()) as Record<string, number> | undefined;
    return row ? Object.values(row)[0] : undefined;
  }
  async countTrailingWs(): Promise<number | undefined> {
    const stmt = await this.prepare(
      "countTrailingWs",
      "select count(*) from users ;",
    );
    const row = (await stmt.get()) as Record<string, number> | undefined;
    return row ? Object.values(row)[0] : undefined;
  }
  async getBigints(): Promise<
    { posts: number | null; total: number } | undefined
  > {
    const stmt = await this.prepare(
      "getBigints",
      "select posts, total from bigints where id = 1;",
    );
    return (await stmt.get()) as
      | { posts: number | null; total: number }
      | undefined;
  }
  async users4(): Promise<{ email: string | null; name: string } | undefined> {
    const stmt = await this.prepare(
      "users4",
      `select email, name from users where id = '1';`,
    );
    return (await stmt.get()) as
      | { email: string | null; name: string }
      | undefined;
  }
  async users5(): Promise<{ count: number; email: string | null }[]> {
    const stmt = await this.prepare(
      "users5",
      `select 10 count, email from users where id = '1';`,
    );
    return (await stmt.all()) as { count: number; email: string | null }[];
  }
  async users6(
    name: string,
  ): Promise<{ id: string; name: string; email: string } | undefined> {
    const stmt = await this.prepare(
      "users6",
      "SELECT * FROM users WHERE name =?",
    );
    return (await stmt.get(name)) as
      | { id: string; name: string; email: string }
      | undefined;
  }
  async users7(
    name: string,
  ): Promise<{ id: string; name: string; email: string | null }[]> {
    const stmt = await this.prepare(
      "users7",
      "SELECT * FROM users WHERE name =?",
    );
    return (await stmt.all(name)) as {
      id: string;
      name: string;
      email: string | null;
    }[];
  }
  async reservedWordTest(): Promise<
    { class: string; type: string } | undefined
  > {
    const stmt = await this.prepare(
      "reserved_word_test",
      `SELECT name as class, email as type FROM users WHERE id = '1'`,
    );
    return (await stmt.get()) as { class: string; type: string } | undefined;
  }
}
